/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "surface-bright": "#f7f9fb",
          "on-primary-fixed": "#00174b",
          "secondary-fixed-dim": "#bec6e0",
          "on-secondary-fixed-variant": "#3f465c",
          "on-primary-fixed-variant": "#003ea8",
          "surface-variant": "#e0e3e5",
          "surface-container": "#eceef0",
          "on-primary-container": "#eeefff",
          "inverse-surface": "#2d3133",
          "inverse-primary": "#b4c5ff",
          "on-surface-variant": "#434655",
          "outline-variant": "#c3c6d7",
          "error": "#ba1a1a",
          "background": "#f7f9fb",
          "surface-container-lowest": "#ffffff",
          "inverse-on-surface": "#eff1f3",
          "on-tertiary-fixed": "#0b1c30",
          "on-secondary-fixed": "#131b2e",
          "on-error-container": "#93000a",
          "surface-container-high": "#e6e8ea",
          "tertiary-fixed-dim": "#b7c8e1",
          "tertiary-fixed": "#d3e4fe",
          "surface-container-highest": "#e0e3e5",
          "primary": "#004ac6",
          "error-container": "#ffdad6",
          "secondary-container": "#dae2fd",
          "on-tertiary": "#ffffff",
          "secondary": "#565e74",
          "surface": "#f7f9fb",
          "surface-dim": "#d8dadc",
          "surface-container-low": "#f2f4f6",
          "secondary-fixed": "#dae2fd",
          "on-error": "#ffffff",
          "on-surface": "#191c1e",
          "primary-fixed": "#dbe1ff",
          "on-secondary-container": "#5c647a",
          "surface-tint": "#0053db",
          "tertiary-container": "#5e6e85",
          "tertiary": "#46566c",
          "on-background": "#191c1e",
          "on-tertiary-fixed-variant": "#38485d",
          "on-primary": "#ffffff",
          "on-tertiary-container": "#e9f0ff",
          "outline": "#737686",
          "primary-fixed-dim": "#b4c5ff",
          "on-secondary": "#ffffff",
          "primary-container": "#2563eb"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "spacing": {
          "gutter": "16px",
          "column-gap": "24px",
          "margin-desktop": "32px",
          "base": "4px",
          "margin-mobile": "16px"
      },
      "fontFamily": {
          "body-lg": ["Inter", "sans-serif"],
          "label-md": ["Inter", "sans-serif"],
          "label-sm": ["Inter", "sans-serif"],
          "body-md": ["Inter", "sans-serif"],
          "headline-sm": ["Inter", "sans-serif"],
          "headline-md": ["Inter", "sans-serif"],
          "headline-lg": ["Inter", "sans-serif"],
          "headline-lg-mobile": ["Inter", "sans-serif"],
          "sans": ["Inter", "sans-serif"],
          "display": ["Inter", "sans-serif"]
      },
      "fontSize": {
          "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
          "label-md": ["13px", { "lineHeight": "18px", "letterSpacing": "0.01em", "fontWeight": "500" }],
          "label-sm": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
          "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
          "headline-sm": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
          "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
          "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
          "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
