import { useEffect, useState } from 'react';
import { collection, getDocs } from 'firebase/firestore';
import { httpsCallable } from 'firebase/functions';
import { db, functions } from '../firebase';
import { ScoreBadge, StatusPill, Spinner } from '../components/Shared';

export default function MatchesPage() {
  const [matches, setMatches] = useState([]);
  const [companies, setCompanies] = useState({});
  const [contributors, setContributors] = useState({});
  const [loading, setLoading] = useState(true);
  const [filterStatus, setFilterStatus] = useState('');
  const [sortBy, setSortBy] = useState('score');

  useEffect(() => {
    async function load() {
      // Load name lookup maps
      const compSnap = await getDocs(collection(db, 'companies'));
      const compMap = {};
      compSnap.forEach((d) => { compMap[d.id] = d.data().name; });
      setCompanies(compMap);

      const contSnap = await getDocs(collection(db, 'contributors'));
      const contMap = {};
      contSnap.forEach((d) => { contMap[d.id] = d.data().name; });
      setContributors(contMap);

      // Load all relationships
      const relSnap = await getDocs(collection(db, 'relationships'));
      const list = [];
      relSnap.forEach((d) => list.push({ id: d.id, ...d.data() }));
      setMatches(list);
      setLoading(false);
    }
    load();
  }, []);

  async function handleStatusChange(relId, newStatus) {
    try {
      const updateStatus = httpsCallable(functions, 'update_relationship_status');
      await updateStatus({ relationshipId: relId, newStatus });
      setMatches((prev) =>
        prev.map((m) => (m.id === relId ? { ...m, status: newStatus } : m))
      );
    } catch (e) {
      console.error('Failed to update status:', e);
      alert('Failed to update. Check emulator logs.');
    }
  }

  if (loading) return <Spinner />;

  let filtered = matches;
  if (filterStatus) {
    filtered = filtered.filter((m) => m.status === filterStatus);
  }

  if (sortBy === 'score') {
    filtered.sort((a, b) => (b.aiMatchScore || 0) - (a.aiMatchScore || 0));
  }

  return (
    <div>
      <div className="page-header">
        <h2>AI Matches</h2>
        <p>{matches.length} total relationships generated by the AI engine</p>
      </div>

      <div className="filter-bar">
        <select value={filterStatus} onChange={(e) => setFilterStatus(e.target.value)}>
          <option value="">All Statuses</option>
          <option value="Recommended">Recommended</option>
          <option value="Approved">Approved</option>
          <option value="Active">Active</option>
          <option value="Rejected">Rejected</option>
          <option value="Completed">Completed</option>
        </select>
        <select value={sortBy} onChange={(e) => setSortBy(e.target.value)}>
          <option value="score">Sort by Score (High → Low)</option>
        </select>
      </div>

      <div className="card">
        {filtered.length === 0 ? (
          <div className="empty-state"><p>No matches found.</p></div>
        ) : (
          <table className="data-table">
            <thead>
              <tr>
                <th>Company</th>
                <th>Contributor</th>
                <th>Type</th>
                <th>Score</th>
                <th>AI Explanation</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((m) => (
                <tr key={m.id}>
                  <td style={{ fontWeight: 600 }}>{companies[m.sourceId] || m.sourceId}</td>
                  <td style={{ fontWeight: 500 }}>{contributors[m.targetId] || m.targetId}</td>
                  <td style={{ fontSize: 12 }}>{m.type}</td>
                  <td><ScoreBadge score={m.aiMatchScore} /></td>
                  <td className="match-explanation">{m.aiExplanation?.substring(0, 150)}...</td>
                  <td><StatusPill status={m.status} /></td>
                  <td>
                    <div className="match-actions">
                      {m.status === 'Recommended' && (
                        <>
                          <button
                            className="btn btn-sm btn-success"
                            onClick={() => handleStatusChange(m.id, 'Approved')}
                          >
                            Approve
                          </button>
                          <button
                            className="btn btn-sm btn-danger"
                            onClick={() => handleStatusChange(m.id, 'Rejected')}
                          >
                            Reject
                          </button>
                        </>
                      )}
                      {m.status === 'Approved' && (
                        <button
                          className="btn btn-sm btn-primary"
                          onClick={() => handleStatusChange(m.id, 'Active')}
                        >
                          Activate
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}
